server:
  port: 8086

spring:
  application:
    name: web

eureka:
  client:
    fetch-registry: true #是否从eureka服务器获取各个微服务地址
    register-with-eureka: true #是否注册到eureka服务器
    service-url:
      defaultZone: http://localhost:2020/eureka/

feign:
  hystrix:
    enabled: true  #开启熔断，默认为false  熔断:如果访问的地址不可用，直接返回。防止发生雪崩
